StartupEvents.registry("item", (event) => {
    event
        .create("lilliput_cloak")
        .attachCuriosCapability(
            CuriosJSCapabilityBuilder.create().addAttribute(
                "minecraft:generic.scale",
                "7520dd31-0c06-4351-ba72-db73ce882367",
                -0.56,
                "add_multiplied_base"
            )
        )
        .maxStackSize(1)
        .tag("curios:belt");
    event
        .create("brobdingnag_cloak")
        .attachCuriosCapability(
            CuriosJSCapabilityBuilder.create()
                .addAttribute(
                    "minecraft:generic.scale",
                    "7520dd31-0c06-4351-ba72-db73ce882367",
                    0.4,
                    "add_multiplied_base"
                )
                .addAttribute(
                    "generic.movement_speed",
                    "7520dd31-0c06-4351-ba72-db73ce882367",
                    0.2,
                    "add_multiplied_base"
                )
                .addAttribute(
                    "dragonsurvival:dragon_breath_range",
                    "7520dd31-0c06-4351-ba72-db73ce882367",
                    0.5,
                    "add_multiplied_base"
                )
                .addAttribute(
                    "dragonsurvival:flight_speed",
                    "7520dd31-0c06-4351-ba72-db73ce882367",
                    0.5,
                    "add_multiplied_base"
                )
                .addAttribute(
                    "dragonsurvival:flight_stamina",
                    "7520dd31-0c06-4351-ba72-db73ce882367",
                    0.2,
                    "add_multiplied_base"
                )
        )
        .maxStackSize(1)
        .tag("curios:belt");
});
